name: 'CI'

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - 'main'

jobs:
  build:
    name: Build and Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # uses script https://github.com/oracle-actions/setup-java
      - name: Download Java
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle' # See 'Supported distributions' for available options
          java-version: '21'

      - name: Build
        run: mvn --batch-mode -DskipTests package

      - name: Test
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true test

      - name: Upload Artifact GitHub Action
        uses: actions/upload-artifact@v2
        with:
          name: testResults
          path: /home/runner/work/junit-example/junit-example/target/surefire-reports
